In [1]:
import numpy as np

def create_border_matrix(rows, cols):
  """Creates a NumPy matrix with ones at the borders and zeros inside."""
  matrix = np.ones((rows, cols))
  matrix[1:-1, 1:-1] = 0
  return matrix

matrix_5x5 = create_border_matrix(5, 5)
print(matrix_5x5)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [2]:
import numpy as np

def create_diagonal_matrix(size):
  """Creates a square matrix with diagonals set to 1 and 2, and other elements to 3."""
  matrix = np.full((size, size), 3)  # Initialize with 3s

  for i in range(size):
    matrix[i, i] = 1  # Set primary diagonal to 1
    matrix[i, size - 1 - i] = 2 # set secondary diagonal to 2

  return matrix

matrix_5x5 = create_diagonal_matrix(5)
print(matrix_5x5)

[[1 3 3 3 2]
 [3 1 3 2 3]
 [3 3 2 3 3]
 [3 2 3 1 3]
 [2 3 3 3 1]]
